### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by TPeterW** [TPeterW/MiddRides-Android#1]
> "We should use Fragment for everything!"

says Nosagie, grim and gloomy.

So this discussion is for posting opinions and comments on UI design.

**Comment by TPeterW** [comment]
## Version 0:
Currently we have three pages:
1. MainScreen with a floating action button to call for service, a button on action bar for login which hides after successful login and a button directing to settings
2. LoginPage with normal login stuff, nothing at stake
3. Settings with a Fragment including preferences

**Comment by Nosagie** [comment]
Did you take a look at my branch?

**Comment by TPeterW** [comment]
Yes, but not carefully, can you upload it to the new "Fragmentise" branch please?

**Comment by TPeterW** [comment]
Closed because we now have a design from artsy artist.
