### ISSUE TITLE
update passengersWaiting in the Location table for each new request

### ISSUE THREAD

**Issue by sherifnada** [TPeterW/MiddRides-Android#10]
add 1 when a passenger requests, flush to 0 when a dispatcher alerts location of arrival

**Comment by TPeterW** [comment]
I don't think it's the job of the passenger (a.k.a. mobile) to clean the table, the table should be cleaned when the push notification is sent from the web. Mobile should simply add 1 when request is made, and subtract 1when cancelled.

**Comment by TPeterW** [comment]
One other problem about changing passengersWaiting is that we currently set all the Location entries as ReadOnly to protect them from being edited. I changed it to Read and Write for now, but we probably should move this to another class.

**Comment by sherifnada** [comment]
Agreed, clearing the table will be done on the backend. Did you implement the "add 1" functionality?

**Comment by TPeterW** [comment]
Yes, but I still think we should do it the other way and keep the Location class ReadOnly, as mentioned above.

**Comment by sherifnada** [comment]
That's a better idea. Wanna do that?

**Comment by TPeterW** [comment]
So where should we move that field to? Or just a new LocationStatus class, with all possible future fields to add?

**Comment by sherifnada** [comment]
Was this implemented?

**Comment by TPeterW** [comment]
yes

**Comment by sherifnada** [comment]
y u so good

**Comment by TPeterW** [comment]
I know
