### ISSUE TITLE
Move "cancel request" from settings view to vanRequest view

### ISSUE THREAD

**Issue by sherifnada** [TPeterW/MiddRides-Android#11]
might be already implemented, but adding for completeness.

**Comment by TPeterW** [comment]
One problem if we do that: we will lose the Floating Action Button, which means we cannot use SnackBar any more, and then we might go back to a more ugly way of warning.

**Comment by sherifnada** [comment]
Floating action is the button with the alarm drawn on it?

**Comment by TPeterW** [comment]
Yes, and SnackBar is the bar that pops up from below.

**Comment by TPeterW** [comment]
I don't like this design, it gives people the temptation to cancel their request. 乁( ◔ ౪◔)「

**Comment by sherifnada** [comment]
^less load on the server

**Comment by TPeterW** [comment]
I still don't like this. This is a formal protest. (｡・`ω´･)

**Comment by TPeterW** [comment]
Done.
