### ISSUE TITLE
resetView() not safe

### ISSUE THREAD

**Issue by TPeterW** [TPeterW/MiddRides-Android#23]
Possible scenario:
1. User makes request, and gets notified, countdown starts.
2. User cancels request, everything back to normal, countdown still going!
3. Within 5 minutes from the first request, user makes another one, soon the view is going to get reset.

Possible solutions:
1. Unregister this reset handler on cancelling request (safer and less resource consumed)
2. Add check in resetView function (we should probably do both), this means an extra local field called notified should be added.

**Comment by sherifnada** [comment]
All good ideas. Would you be comfortable doing #1? I already have a
sharedPreference that contains a notified field, is that what you are
talking about?

**Comment by TPeterW** [comment]
Finished, see UI branch
