### ISSUE TITLE
Remove the light blue frame from the request van button, and replace the "middrides" text under the van with the button 

### ISSUE THREAD

**Issue by sherifnada** [TPeterW/MiddRides-Android#28]

**Comment by TPeterW** [comment]
I just realized another problem as I am doing it. If a person clicks on the button, the image changes to the gif, do the users also click on the gif that is running to cancel the request?

**Comment by sherifnada** [comment]
No, we just change the button to a cancel button and the gif can be a
separate thing

**Comment by TPeterW** [comment]
I left the text "MiddRides" in though, thought it be the best.

**Comment by sherifnada** [comment]
Good call, agreed
